package es.tid.topologyModuleBase.TAPITopoModel.api;

import es.tid.topologyModuleBase.TAPITopoModel.api.*;
import es.tid.topologyModuleBase.TAPITopoModel.model.*;

import org.glassfish.jersey.media.multipart.FormDataContentDisposition;

import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse200;
import es.tid.topologyModuleBase.TAPITopoModel.model.ExtensionsSpec;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse2001;
import es.tid.topologyModuleBase.TAPITopoModel.model.NameAndValue;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse2002;
import es.tid.topologyModuleBase.TAPITopoModel.model.NwTopologyServiceSchema;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse2004;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20029;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse2006;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20014;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse2005;
import es.tid.topologyModuleBase.TAPITopoModel.model.Link;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse2008;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse2007;
import es.tid.topologyModuleBase.TAPITopoModel.model.LinkPort;
import es.tid.topologyModuleBase.TAPITopoModel.model.LayerProtocolTransitionPac;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20015;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse2009;
import es.tid.topologyModuleBase.TAPITopoModel.model.RiskCharacteristic;
import es.tid.topologyModuleBase.TAPITopoModel.model.RiskParameterPac;
import es.tid.topologyModuleBase.TAPITopoModel.model.AdminStatePac;
import es.tid.topologyModuleBase.TAPITopoModel.model.Capacity;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20010;
import es.tid.topologyModuleBase.TAPITopoModel.model.TransferCapacityPac;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20011;
import es.tid.topologyModuleBase.TAPITopoModel.model.CostCharacteristic;
import es.tid.topologyModuleBase.TAPITopoModel.model.TransferCostPac;
import es.tid.topologyModuleBase.TAPITopoModel.model.TransferIntegrityPac;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20012;
import es.tid.topologyModuleBase.TAPITopoModel.model.LatencyCharacteristic;
import es.tid.topologyModuleBase.TAPITopoModel.model.TransferTimingPac;
import es.tid.topologyModuleBase.TAPITopoModel.model.ValidationPac;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20013;
import es.tid.topologyModuleBase.TAPITopoModel.model.ValidationMechanism;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20030;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20017;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20027;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20028;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20016;
import es.tid.topologyModuleBase.TAPITopoModel.model.Node;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20019;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20022;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20021;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20020;
import es.tid.topologyModuleBase.TAPITopoModel.model.LayerProtocol;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20023;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20018;
import es.tid.topologyModuleBase.TAPITopoModel.model.NodeEdgePoint;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20024;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20025;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse20026;
import es.tid.topologyModuleBase.TAPITopoModel.model.InlineResponse2003;
import es.tid.topologyModuleBase.TAPITopoModel.model.Topology;

import java.util.List;
import es.tid.topologyModuleBase.TAPITopoModel.api.NotFoundException;

import java.io.InputStream;

import javax.ws.rs.core.Response;
import javax.ws.rs.core.SecurityContext;

@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2016-12-28T15:11:12.465+01:00")
public abstract class ConfigApiService {
    public abstract Response retrieveContextNwTopologyServiceExtensionsExtensions(SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextNwTopologyServiceExtensionsExtensionsById(String extensionsSpecification,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextNwTopologyServiceLabelLabel(SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextNwTopologyServiceLabelLabelById(String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextNwTopologyServiceNameName(SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextNwTopologyServiceNameNameById(String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextNwTopologyServiceNwTopologyService(SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyExtensionsExtensions(String uuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyExtensionsExtensionsById(String uuid,String extensionsSpecification,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLabelLabel(String uuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLabelLabelById(String uuid,String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkExtensionsExtensions(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkExtensionsExtensionsById(String uuid,String linkUuid,String extensionsSpecification,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkLabelLabel(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkLabelLabelById(String uuid,String linkUuid,String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkLink(String uuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkLinkById(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkLinkPortExtensionsExtensions(String uuid,String linkUuid,String localId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkLinkPortExtensionsExtensionsById(String uuid,String linkUuid,String localId,String extensionsSpecification,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkLinkPortLinkPort(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkLinkPortLinkPortById(String uuid,String linkUuid,String localId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkLpTransitionLpTransition(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkNameName(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkNameNameById(String uuid,String linkUuid,String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkRiskParameterRiskCharacteristicRiskCharacteristic(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkRiskParameterRiskCharacteristicRiskCharacteristicById(String uuid,String linkUuid,String riskCharacteristicName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkRiskParameterRiskParameter(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkStateState(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferCapacityAvailableCapacityAvailableCapacity(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferCapacityCapacityAssignedToUserViewCapacityAssignedToUserView(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferCapacityCapacityAssignedToUserViewCapacityAssignedToUserViewById(String uuid,String linkUuid,String totalSize,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferCapacityTotalPotentialCapacityTotalPotentialCapacity(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferCapacityTransferCapacity(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferCostCostCharacteristicCostCharacteristic(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferCostCostCharacteristicCostCharacteristicCostName(String uuid,String linkUuid,String costName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferCostTransferCost(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferIntegrityTransferIntegrity(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferTimingLatencyCharacteristicLatencyCharacteristic(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferTimingLatencyCharacteristicLatencyCharacteristicTrafficPropertyName(String uuid,String linkUuid,String trafficPropertyName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkTransferTimingTransferTiming(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkValidationValidation(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkValidationValidationMechanismValidationMechanism(String uuid,String linkUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyLinkValidationValidationMechanismValidationMechanismValidationMechanism(String uuid,String linkUuid,String validationMechanism,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNameName(String uuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNameNameById(String uuid,String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeExtensionsExtensions(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeExtensionsExtensionsById(String uuid,String nodeUuid,String extensionsSpecification,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeLabelLabel(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeLabelLabelById(String uuid,String nodeUuid,String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeNameName(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeNameNameById(String uuid,String nodeUuid,String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeNode(String uuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeNodeById(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointExtensionsExtensions(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointExtensionsExtensionsById(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,String extensionsSpecification,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointLabelLabel(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointLabelLabelById(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointLayerProtocolExtensionsExtensions(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,String localId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointLayerProtocolExtensionsExtensionsById(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,String localId,String extensionsSpecification,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointLayerProtocolLayerProtocol(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointLayerProtocolLayerProtocolById(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,String localId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointNameName(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointNameNameById(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,String valueName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointOwnedNodeEdgePoint(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointOwnedNodeEdgePointById(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeOwnedNodeEdgePointStateState(String uuid,String nodeUuid,String ownedNodeEdgePointUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeStateState(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferCapacityAvailableCapacityAvailableCapacity(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferCapacityCapacityAssignedToUserViewCapacityAssignedToUserView(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferCapacityCapacityAssignedToUserViewCapacityAssignedToUserViewById(String uuid,String nodeUuid,String totalSize,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferCapacityTotalPotentialCapacityTotalPotentialCapacity(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferCapacityTransferCapacity(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferCostCostCharacteristicCostCharacteristic(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferCostCostCharacteristicCostCharacteristicCostName(String uuid,String nodeUuid,String costName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferCostTransferCost(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferIntegrityTransferIntegrity(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferTimingLatencyCharacteristicLatencyCharacteristic(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferTimingLatencyCharacteristicLatencyCharacteristicTrafficPropertyName(String uuid,String nodeUuid,String trafficPropertyName,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyNodeTransferTimingTransferTiming(String uuid,String nodeUuid,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyTopology(SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveContextTopologyTopologyById(String uuid,SecurityContext securityContext) throws NotFoundException;
}
