package es.tid.topologyModuleBase.UnifyTopoModel.api;

import es.tid.topologyModuleBase.UnifyTopoModel.api.*;
import es.tid.topologyModuleBase.UnifyTopoModel.model.*;

import com.sun.jersey.core.header.FormDataContentDisposition;

import es.tid.topologyModuleBase.UnifyTopoModel.model.VirtualizerSchema;
import es.tid.topologyModuleBase.UnifyTopoModel.model.Link;
import es.tid.topologyModuleBase.UnifyTopoModel.model.LinkResource;
import es.tid.topologyModuleBase.UnifyTopoModel.model.LinksSchema;
import es.tid.topologyModuleBase.UnifyTopoModel.model.MetadataSchema;
import es.tid.topologyModuleBase.UnifyTopoModel.model.CapabilitiesSchema;
import es.tid.topologyModuleBase.UnifyTopoModel.model.Node;
import es.tid.topologyModuleBase.UnifyTopoModel.model.AddressesSchema;
import es.tid.topologyModuleBase.UnifyTopoModel.model.L3Address;
import es.tid.topologyModuleBase.UnifyTopoModel.model.ControlSchema;
import es.tid.topologyModuleBase.UnifyTopoModel.model.Port;
import es.tid.topologyModuleBase.UnifyTopoModel.model.SapDataSchema;
import es.tid.topologyModuleBase.UnifyTopoModel.model.PortsSchema;
import es.tid.topologyModuleBase.UnifyTopoModel.model.SoftwareResource;
import es.tid.topologyModuleBase.UnifyTopoModel.model.Nodes;
import es.tid.topologyModuleBase.UnifyTopoModel.model.Flowentry;
import es.tid.topologyModuleBase.UnifyTopoModel.model.FlowtableSchema;
import es.tid.topologyModuleBase.UnifyTopoModel.model.InfraNode;
import es.tid.topologyModuleBase.UnifyTopoModel.model.NodesSchema;

import java.util.List;
import es.tid.topologyModuleBase.UnifyTopoModel.api.NotFoundException;

import java.io.InputStream;

import javax.ws.rs.core.Response;
import javax.ws.rs.core.SecurityContext;

@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2016-07-26T10:14:24.517Z")
public abstract class ConfigApiService {
    public abstract Response createVirtualizerById(VirtualizerSchema virtualizer,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerLinksLinkLinkById(String id,Link link,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerLinksLinkResourcesResourcesById(String id,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerLinksLinksById(LinksSchema links,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerMetadataMetadataById(String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesCapabilitiesById(String id,CapabilitiesSchema capabilities,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinkLinkById(String id,String odeId,String inkId,Link link,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinkResourcesResourcesById(String id,String odeId,String inkId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinksById(String id,String odeId,LinksSchema links,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodeMetadataMetadataById(String id,String odeId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodeNodeById(String id,String odeId,Node node,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortAddressesAddressesById(String id,String odeId,String ortId,AddressesSchema addresses,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortAddressesL3L3ById(String id,String odeId,String ortId,String _3Id,L3Address l3,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortControlControlById(String id,String odeId,String ortId,ControlSchema control,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortMetadataMetadataById(String id,String odeId,String ortId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortPortById(String id,String odeId,String ortId,Port port,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortSapDataResourcesResourcesById(String id,String odeId,String ortId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortSapDataSapDataById(String id,String odeId,String ortId,SapDataSchema sapData,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortsById(String id,String odeId,PortsSchema ports,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsNodeResourcesResourcesById(String id,String odeId,SoftwareResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeCapabilitiesSupportedNFsSupportedNFsById(String id,Nodes supportedNFs,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeFlowtableFlowentryFlowentryById(String id,String lowentryId,Flowentry flowentry,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeFlowtableFlowentryResourcesResourcesById(String id,String lowentryId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeFlowtableFlowtableById(String id,FlowtableSchema flowtable,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeLinksLinkLinkById(String id,String inkId,Link link,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeLinksLinkResourcesResourcesById(String id,String inkId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeLinksLinksById(String id,LinksSchema links,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeMetadataMetadataById(String id,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNFInstancesById(String id,Nodes nFInstances,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodeLinksLinkLinkById(String id,String odeId,String inkId,Link link,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodeLinksLinkResourcesResourcesById(String id,String odeId,String inkId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodeLinksLinksById(String id,String odeId,LinksSchema links,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodeMetadataMetadataById(String id,String odeId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodeNodeById(String id,String odeId,Node node,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodePortsPortAddressesAddressesById(String id,String odeId,String ortId,AddressesSchema addresses,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodePortsPortAddressesL3L3ById(String id,String odeId,String ortId,String _3Id,L3Address l3,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodePortsPortControlControlById(String id,String odeId,String ortId,ControlSchema control,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodePortsPortMetadataMetadataById(String id,String odeId,String ortId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodePortsPortPortById(String id,String odeId,String ortId,Port port,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodePortsPortSapDataResourcesResourcesById(String id,String odeId,String ortId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodePortsPortSapDataSapDataById(String id,String odeId,String ortId,SapDataSchema sapData,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodePortsPortsById(String id,String odeId,PortsSchema ports,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNFInstancesNodeResourcesResourcesById(String id,String odeId,SoftwareResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeNodeById(String id,InfraNode node,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodePortsPortAddressesAddressesById(String id,String ortId,AddressesSchema addresses,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodePortsPortAddressesL3L3ById(String id,String ortId,String _3Id,L3Address l3,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodePortsPortControlControlById(String id,String ortId,ControlSchema control,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodePortsPortMetadataMetadataById(String id,String ortId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodePortsPortPortById(String id,String ortId,Port port,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodePortsPortSapDataResourcesResourcesById(String id,String ortId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodePortsPortSapDataSapDataById(String id,String ortId,SapDataSchema sapData,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodePortsPortsById(String id,PortsSchema ports,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodeResourcesResourcesById(String id,SoftwareResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response createVirtualizerNodesNodesById(NodesSchema nodes,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerById(SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerLinksLinkLinkById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerLinksLinkResourcesResourcesById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerLinksLinksById(SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerMetadataMetadataById(String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesCapabilitiesById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinkLinkById(String id,String odeId,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinkResourcesResourcesById(String id,String odeId,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinksById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodeMetadataMetadataById(String id,String odeId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodeNodeById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortAddressesAddressesById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortAddressesL3L3ById(String id,String odeId,String ortId,String _3Id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortControlControlById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortMetadataMetadataById(String id,String odeId,String ortId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortPortById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortSapDataResourcesResourcesById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortSapDataSapDataById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortsById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsNodeResourcesResourcesById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeCapabilitiesSupportedNFsSupportedNFsById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeFlowtableFlowentryFlowentryById(String id,String lowentryId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeFlowtableFlowentryResourcesResourcesById(String id,String lowentryId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeFlowtableFlowtableById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeLinksLinkLinkById(String id,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeLinksLinkResourcesResourcesById(String id,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeLinksLinksById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeMetadataMetadataById(String id,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNFInstancesById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodeLinksLinkLinkById(String id,String odeId,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodeLinksLinkResourcesResourcesById(String id,String odeId,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodeLinksLinksById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodeMetadataMetadataById(String id,String odeId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodeNodeById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodePortsPortAddressesAddressesById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodePortsPortAddressesL3L3ById(String id,String odeId,String ortId,String _3Id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodePortsPortControlControlById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodePortsPortMetadataMetadataById(String id,String odeId,String ortId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodePortsPortPortById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodePortsPortSapDataResourcesResourcesById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodePortsPortSapDataSapDataById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodePortsPortsById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNFInstancesNodeResourcesResourcesById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeNodeById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodePortsPortAddressesAddressesById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodePortsPortAddressesL3L3ById(String id,String ortId,String _3Id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodePortsPortControlControlById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodePortsPortMetadataMetadataById(String id,String ortId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodePortsPortPortById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodePortsPortSapDataResourcesResourcesById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodePortsPortSapDataSapDataById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodePortsPortsById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodeResourcesResourcesById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response deleteVirtualizerNodesNodesById(SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizer(SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerLinksLinkLinkById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerLinksLinkResourcesResourcesById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerLinksLinks(SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerMetadataMetadataById(String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesCapabilitiesById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinkLinkById(String id,String odeId,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinkResourcesResourcesById(String id,String odeId,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinksById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodeMetadataMetadataById(String id,String odeId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodeNodeById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortAddressesAddressesById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortAddressesL3L3ById(String id,String odeId,String ortId,String _3Id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortControlControlById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortMetadataMetadataById(String id,String odeId,String ortId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortPortById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortSapDataResourcesResourcesById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortSapDataSapDataById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortsById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsNodeResourcesResourcesById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeCapabilitiesSupportedNFsSupportedNFsById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeFlowtableFlowentryFlowentryById(String id,String lowentryId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeFlowtableFlowentryResourcesResourcesById(String id,String lowentryId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeFlowtableFlowtableById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeLinksLinkLinkById(String id,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeLinksLinkResourcesResourcesById(String id,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeLinksLinksById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeMetadataMetadataById(String id,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNFInstancesById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodeLinksLinkLinkById(String id,String odeId,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodeLinksLinkResourcesResourcesById(String id,String odeId,String inkId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodeLinksLinksById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodeMetadataMetadataById(String id,String odeId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodeNodeById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodePortsPortAddressesAddressesById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodePortsPortAddressesL3L3ById(String id,String odeId,String ortId,String _3Id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodePortsPortControlControlById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodePortsPortMetadataMetadataById(String id,String odeId,String ortId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodePortsPortPortById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodePortsPortSapDataResourcesResourcesById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodePortsPortSapDataSapDataById(String id,String odeId,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodePortsPortsById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNFInstancesNodeResourcesResourcesById(String id,String odeId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeNodeById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodePortsPortAddressesAddressesById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodePortsPortAddressesL3L3ById(String id,String ortId,String _3Id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodePortsPortControlControlById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodePortsPortMetadataMetadataById(String id,String ortId,String key,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodePortsPortPortById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodePortsPortSapDataResourcesResourcesById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodePortsPortSapDataSapDataById(String id,String ortId,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodePortsPortsById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodeResourcesResourcesById(String id,SecurityContext securityContext) throws NotFoundException;
    public abstract Response retrieveVirtualizerNodesNodes(SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerById(VirtualizerSchema virtualizer,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerLinksLinkLinkById(String id,Link link,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerLinksLinkResourcesResourcesById(String id,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerLinksLinksById(LinksSchema links,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerMetadataMetadataById(String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesCapabilitiesById(String id,CapabilitiesSchema capabilities,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinkLinkById(String id,String odeId,String inkId,Link link,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinkResourcesResourcesById(String id,String odeId,String inkId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodeLinksLinksById(String id,String odeId,LinksSchema links,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodeMetadataMetadataById(String id,String odeId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodeNodeById(String id,String odeId,Node node,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortAddressesAddressesById(String id,String odeId,String ortId,AddressesSchema addresses,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortAddressesL3L3ById(String id,String odeId,String ortId,String _3Id,L3Address l3,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortControlControlById(String id,String odeId,String ortId,ControlSchema control,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortMetadataMetadataById(String id,String odeId,String ortId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortPortById(String id,String odeId,String ortId,Port port,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortSapDataResourcesResourcesById(String id,String odeId,String ortId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortSapDataSapDataById(String id,String odeId,String ortId,SapDataSchema sapData,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodePortsPortsById(String id,String odeId,PortsSchema ports,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsNodeResourcesResourcesById(String id,String odeId,SoftwareResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeCapabilitiesSupportedNFsSupportedNFsById(String id,Nodes supportedNFs,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeFlowtableFlowentryFlowentryById(String id,String lowentryId,Flowentry flowentry,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeFlowtableFlowentryResourcesResourcesById(String id,String lowentryId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeFlowtableFlowtableById(String id,FlowtableSchema flowtable,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeLinksLinkLinkById(String id,String inkId,Link link,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeLinksLinkResourcesResourcesById(String id,String inkId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeLinksLinksById(String id,LinksSchema links,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeMetadataMetadataById(String id,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNFInstancesById(String id,Nodes nFInstances,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodeLinksLinkLinkById(String id,String odeId,String inkId,Link link,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodeLinksLinkResourcesResourcesById(String id,String odeId,String inkId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodeLinksLinksById(String id,String odeId,LinksSchema links,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodeMetadataMetadataById(String id,String odeId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodeNodeById(String id,String odeId,Node node,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodePortsPortAddressesAddressesById(String id,String odeId,String ortId,AddressesSchema addresses,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodePortsPortAddressesL3L3ById(String id,String odeId,String ortId,String _3Id,L3Address l3,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodePortsPortControlControlById(String id,String odeId,String ortId,ControlSchema control,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodePortsPortMetadataMetadataById(String id,String odeId,String ortId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodePortsPortPortById(String id,String odeId,String ortId,Port port,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodePortsPortSapDataResourcesResourcesById(String id,String odeId,String ortId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodePortsPortSapDataSapDataById(String id,String odeId,String ortId,SapDataSchema sapData,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodePortsPortsById(String id,String odeId,PortsSchema ports,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNFInstancesNodeResourcesResourcesById(String id,String odeId,SoftwareResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeNodeById(String id,InfraNode node,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodePortsPortAddressesAddressesById(String id,String ortId,AddressesSchema addresses,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodePortsPortAddressesL3L3ById(String id,String ortId,String _3Id,L3Address l3,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodePortsPortControlControlById(String id,String ortId,ControlSchema control,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodePortsPortMetadataMetadataById(String id,String ortId,String key,MetadataSchema metadata,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodePortsPortPortById(String id,String ortId,Port port,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodePortsPortSapDataResourcesResourcesById(String id,String ortId,LinkResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodePortsPortSapDataSapDataById(String id,String ortId,SapDataSchema sapData,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodePortsPortsById(String id,PortsSchema ports,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodeResourcesResourcesById(String id,SoftwareResource resources,SecurityContext securityContext) throws NotFoundException;
    public abstract Response updateVirtualizerNodesNodesById(NodesSchema nodes,SecurityContext securityContext) throws NotFoundException;
}
